/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/Boletim`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/RegisterStudent`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/Grades`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/RegisterProf`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/RegisterSubject`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/StudentsBySubject`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/SubjectsByProfessor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/app_scholar/Boletim`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/app_scholar/RegisterStudent`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/app_scholar/Grades`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/app_scholar/RegisterProf`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/app_scholar/RegisterSubject`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/app_scholar/StudentsBySubject`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/app_scholar/SubjectsByProfessor`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../screens/app_scholar/Boletim${`?${string}` | `#${string}` | ''}` | `/../screens/app_scholar/RegisterStudent${`?${string}` | `#${string}` | ''}` | `/../screens/app_scholar/Grades${`?${string}` | `#${string}` | ''}` | `/../screens/app_scholar/RegisterProf${`?${string}` | `#${string}` | ''}` | `/../screens/app_scholar/RegisterSubject${`?${string}` | `#${string}` | ''}` | `/../screens/app_scholar/StudentsBySubject${`?${string}` | `#${string}` | ''}` | `/../screens/app_scholar/SubjectsByProfessor${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/Boletim`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/RegisterStudent`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/Grades`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/RegisterProf`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/RegisterSubject`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/StudentsBySubject`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/app_scholar/SubjectsByProfessor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
